### ISSUE TITLE
Create a MessageReceivedEventListener to receive the message initiating LFG command

### ISSUE THREAD

**Issue by colinobriendev** [colinobriendev/RaidBot#3]

**Comment by colinobriendev** [comment]
Should handle argument parsing and user parsing from the LFG command.

**Comment by laurenbarry00** [comment]
Create a MessageReceivedEventListener to handle incoming messages.

Ignore unwanted messages such as those from the bot, those from the bot itself, and those that don't start with the command prefix.

Perform simple string parsing (separating string by whitespace) to determine the command that was run, and store arguments in a list.

If the user ran a recognized command, pass the Event object and the arguments to the appropriate command handler.

**Comment by colinobriendev** [comment]
Closing this due to no need to implement.
