### ISSUE TITLE
Upgrade to JDA 5

### ISSUE THREAD

**Issue by colinobriendev** [colinobriendev/RaidBot#35]
We will need JDA 5 to implement some of our new feature ideas. This should take priority before any other new issues outside of critical bug fixes.

**Comment by aedandan** [comment]
JDA 5's beta is now stable enough to perform an upgrade. See #43, #44, #45, #46 for initial changes,

**Comment by colinobriendev** [comment]
Closing since PR's #48 and #50 is complete
