### ISSUE TITLE
Message Building with JDA 5

### ISSUE THREAD

**Issue by aedandan** [colinobriendev/RaidBot#44]
JDA 4's `MessageBuilder` has been replaced by [`AbstractMessageBuilder`](https://ci.dv8tion.net/job/JDA5/javadoc/net/dv8tion/jda/api/utils/messages/MessageCreateBuilder.html) in JDA 5. Its subclasses are [`MessageCreateBuilder` ](https://ci.dv8tion.net/job/JDA5/javadoc/net/dv8tion/jda/api/utils/messages/MessageCreateBuilder.html) and [`MessageEditBuilder`](https://ci.dv8tion.net/job/JDA5/javadoc/net/dv8tion/jda/api/utils/messages/MessageEditBuilder.html).

**Comment by colinobriendev** [comment]
Closing since #48 didn't close this
